apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cash-in
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/matthy11/k8s-cash-in.git
    targetRevision: HEAD
    path: k8s
  destination: 
    server: https://kubernetes.default.svc
    namespace: cash-in
